[package]
name = "gpudevicemem"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "gpudevicemem"
path = "src/lib.rs"

[features]
cuda9 = ["cuda_blas/cuda9"]

[build-dependencies]
#bindgen = "^0.32"
bindgen = "*"
cc = "*"
walkdir = "*"

[dependencies]
arithmetic = { path = "../arithmetic" }
arrayidx = { path = "../arrayidx" }
cuda = { path = "../libcuda" }
cuda_blas = { path = "../cuda_blas" }
cuda_dnn = { path = "../cuda_dnn" }
cuda_rand = { path = "../cuda_rand" }
float = { path = "../libfloat" }
lazy_static = "*"
memarray = { path = "../memarray" }
#parking_lot = { path = "../parking_lot" }
#parking_lot = "*"
parking_lot = { version = "^0.5", features = ["nightly"] }
